version: "3.7"
services:
  jenkins:
    image: jenkinsci/blueocean
    restart: unless-stopped
    user: root
    ports:
      - "8888:8080"
    volumes:
      - H:\docker-data\jenkins_data:/var/jenkins_home
      - "${HOMEDRIVE}${HOMEPATH}:/home"
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    image: sonarqube
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=coolSonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    depends_on:
      - db
    volumes:
      - H:\docker-data\sonarqube\sonarqube_conf:/opt/sonarqube/conf
      - H:\docker-data\sonarqube\sonarqube_data:/opt/sonarqube/data
      - H:\docker-data\sonarqube\sonarqube_extensions:/opt/sonarqube/extensions
      - H:\docker-data\sonarqube\sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=coolSonar
      - POSTGRES_DB=sonarqube
    volumes:
      - H:\docker-data\postgresql\conf:/var/lib/postgresql
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true