version: '3'
services:
  tests:
    image: openjdk:12-oracle
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - "${CD}:$PWD"
    command: ./gradlew clean build
